version: '3.8'

services:
  backend:
    build: ./backend
    container_name: rifa-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5440/rifasdb
      NODE_ENV: production
    depends_on:
      - db
    networks:
      - rifa-net

  frontend:
    build: ./frontend
    container_name: rifa-frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - rifa-net

  db:
    image: postgres:13
    container_name: rifa-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rifasdb
    volumes:
      - postgres_data:/var/lib/postgresqlrifaapp/data
    networks:
      - rifa-net

volumes:
  postgres_data:

networks:
  rifa-net:
    driver: bridge